name: deploy-staging

run-name: ${{ github.actor }} is rebuilding the site

on: 
    push:
        paths:
            - 'content/**'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts'
      - run: npm install --global @thegetty/quire-cli
      - run: quire --version
      - run: pwd
      - run: ls -la