name: deploy-staging

run-name: ${{ github.actor }} is rebuilding the site

on: push

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: macos-12
    steps:
        - name: Setup Project
          uses: actions/checkout@v4
        
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: '18'
            cache: 'npm'
            cache-dependency-path: package-lock.json
        
        - name: Install Quire
          run: npm install --global @thegetty/quire-cli
        
        - name: Setup Quire Project
          run: |
            quire new build
        
        - name: Remove starter files
          run: |
            rm -rf ./build/content/_assets/images/  
            rm -rf ./build/content/_data/      
            rm ./build/content/*.md
        
        - name: Replace starter files with content files
          run: |
            cp -r ./content/_assets/images/ ./build/content/_assets/images/
            cp -r ./content/_data/ ./build/content/_data/
            cp -r ./content/catalogue/ ./build/content/catalogue/
            cp ./content/*.md ./build/content/

        - name: Build new site
          run: |
            cd ./build/
            quire build

        - name: Check project files
          run: |
            ls -la ./build/

        - name: Log project dependencies
          run: |
            cat ./build/package-lock.json > ./package-lock.json
        
        - name: Save dependencies for caching
          uses: EndBug/add-and-commit@v9
          with:
            add: './package-lock.json'
            message: 'Updating node dependencies from previous build'

        - name: Check website files
          run: |
            ls -la ./build/_site/

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build/_site/