name: deploy-staging

run-name: ${{ github.actor }} is rebuilding the site

on: push

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: macos-12
    steps:
        - name: Setup Project
          uses: actions/checkout@v4
        
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: '18'
        
        - name: Install Quire
          run: npm install --global @thegetty/quire-cli
        
        - name: Setup Quire Project
          run: |
            quire new ra
            ls -al ./ra
        
        - name: Remove files
          run: |
            rm -rf ./ra/content/_assets/images/  
            rm -rf ./ra/content/_data/
            rm -rf ./ra/content/catalog/
            rm -rf ./ra/content/*.md
        
        - name: Copy files
          run: |
            cp -r ./content/_assets/images/ ./ra/content/_assets/images/  
            cp -r ./content/_data/ ./ra/content/_data/
            cp -r ./content/catalog/ ./ra/content/catalog/
            cp ./content/*.md ./ra/content/*.md
        
        - name: Build new site
          run: |
            cd ./ra/
            quire build

        - name: Check project files
          run: |
            ls -la ./ra/

        - name: Check website files
          run: |
            ls -la ./ra/_site/